### PR TITLE
ModalForms API

### PR DESCRIPTION
**Pull request by kvetinac97**
Create them with player.showFormWindow, and then listen to the result with PlayerFormRespondedEvent !!!

### CODE REVIEW

**Comment by yescallop** [comment]
Have you tested all kinds of form elements and they worked? I'll merge if everything is tested ok

**Comment by kvetinac97** [comment]
Everything worked except: Slider did only show, but I was not able to move with it. Probably client or plugin issue (I think I have set wrong min/max/step values)

**Comment by kvetinac97** [comment]
Preview:
shown

**Comment by kvetinac97** [comment]
As you see, only "Tva nalada (od 0 do 10): 0" did not work - not able to move with it. But it is also possible that it was plugin issue, because I don't know what should be the min, max, and step values.

**Comment by yescallop** [comment]
And response handlers can make developing less complex.
e.g. : player.showFormWindow(window, resp -> player.sendMessage(((FormResponseCustom) resp).getInputResponse(0)));
If you could add apis like this, it will be better

**Comment by yescallop** [comment]
too quick to merge? you could open another pull request to fix the bugs found

**Pull request merged**
