### PR TITLE
New Mobs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Snake1999** [comment]
What do you think? @MagicDroidX

**Comment by ghost** [comment]
@Snake1999  its my code ok

**Comment by Snake1999** [comment]
@PikyCZ Of course this is your contribution. I just asked for permission of MDX, he answered "yes" in our qq group, so I did the merge.

**Comment by ghost** [comment]
Can i rewrite and delete unused code? ..

**Comment by Snake1999** [comment]
@PikyCZ yes you can. Push another PR after you finished

**Comment by ghost** [comment]
Ok thanks

**Pull request merged**
