### PR TITLE
Fix teleport client crashes

### PR DESCRIPTION
**Pull request by tigerza117**

### CODE REVIEW

**Comment by vzlomka76** [comment]
I don't have crashes client when i teleport. Why do you need this fix?

**Comment by tigerza117** [comment]
on Disconnect client crashes -....................-

**Comment by vzlomka76** [comment]
@tigerza117 yes, on disconnect client crashes

**Comment by Creeperface01** [comment]
but it must be MCPE bug, because nukkit doesnt send anything on disconnect

**Comment by tigerza117** [comment]
DataPacket PlayStatusPacket client crashes -.......-

**Comment by CraftYourBukkit** [comment]
It is a MCPE bug. In the newest beta it's fixed!

**Comment by Snake1999** [comment]
@CraftYourBukkit I'll check it out

**Pull request closed without merging**
