### PR TITLE
Fix errors that IntelliJ didn't show

### PR DESCRIPTION
**Pull request by ghost**
👍

### CODE REVIEW

**Comment by Creeperface01** [comment]
IntelliJ shows all errors !! :D

**Comment by Creeperface01** [comment]
However I don't think there is a method getLevel(BlockVector3) in level class

**Comment by ghost** [comment]
@Creeperface01 :D

**Comment by ghost** [comment]
https://github.com/ChaptersPE/Nukkit/commit/beb3d908ad96614ea8ed6f2ea2491fc2d0e0fd74

**Pull request closed without merging**
