### PR TITLE
Fix Interact/BlockPlace/Break Events not being called

### LINKED ISSUE #59: PlayerInteractEvent, BlockBreakEvent,BlockPlaceEvent, etc are not working (1.2 branch)
### Issue Description

The events are not called.
### Steps to Reproduce the Issue
Break a block and you can see the BlockBreakEvent isn't called.

### PR DESCRIPTION
**Pull request by kvetinac97**
Yeah!

### CODE REVIEW

**Comment by ghost** [comment]
Cool

**Comment by Goodstuff4UonYT** [comment]
Very nice!

**Comment by ghost** [comment]
@kvetinac97 Thanks, i'm added to my PR. You can close @kvetinac97  👍

**Comment by Snake1999** [comment]
@yescallop Please do some review on this PR

**Pull request merged**
