### PR TITLE
Fix compiling

### PR DESCRIPTION
**Pull request by vzlomka76**
@Creeperface01 added new methods in LevelProvider, but don't added them to LevelDB

### CODE REVIEW

**Review by Creeperface01 — COMMENTED** [review]
But this will cause NPE

**Comment by vzlomka76** [comment]
@Creeperface01 What is NPE?

**Comment by Creeperface01** [comment]
Null pointer exception

**Comment by vzlomka76** [comment]
@Creeperface01 Uh, Then what are the ideas?

**Comment by Creeperface01** [comment]
Look at base level provider

**Comment by vzlomka76** [comment]
@Creeperface01 Ok, I'll redo pull request

**Comment by vzlomka76** [comment]
@Creeperface01 Checked on my server, it works well

**Pull request merged**
